# Generated by Django 4.1.1 on 2023-02-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=120)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=4)),
                ("date_pub", models.DateField(auto_now=True)),
                ("img", models.ImageField(blank=True, null=True, upload_to="media")),
                (
                    "categorie_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurantHananaApp.categorie",
                    ),
                ),
            ],
            options={"ordering": ["date_pub"],},
        ),
    ]
